= Scripture study project
The goal of this project is to create a set of tools 
for the scripture students.

== Project status
	- Wednesday 28 November 2018: Project stated. 
	I want to catalog the bible (old vs new books, chapters, verses).
	For example, how many books in the bible?
	How many Old Testament (OT) books?
	How many New Testament (NT) books?
	How many chapters are there in the book of Matthew?
	How many verses in chapter 1 of the book of Matthew?

== Resources online
Important web sites:

	
	- New American Bible (NAB): `http://www.vatican.va/archive/ENG0839/_INDEX.HTM` or
								`http://www.usccb.org/bible/books-of-the-bible/index.cfm`
	- Revised Standard Version (RSV): `https://quod.lib.umich.edu/r/rsv/browse.html` or
								`https://www.ewtn.com/devotionals/biblesearch.asp`
	- Douay-Rheims (DR) & Latin Vulgate (LV): `http://www.drbo.org/`
	- Abbreviations: `http://catholic-resources.org/Bible/Abbreviations-Abreviaciones.htm`
 
== Cataloging process
The process of cataloging the bible of the four major translation
that is approved by the Catholic Church was through the use
of Selenium WebDriver along with manual corrections of the 
final contents and file names. In the end, the text of the 
bible of the four translations are: New American, Revised Standard,
Douay-Rheims, and Latin Vulgate.

The code for cataloging is in the /src/test file. 

PRESERVED this code in a different branch.

= APACHE SOLR Search Engine
I use Apache Solr to index the text for searching. The code for this 
effort is mostly in the 'query' package.

== Creating a collection
I use this command:

```
./bin/solr create -c bible -s 2 -rf 2
```

== Posting to the collection:

```
./bin/post -c bible /media/kiet/toshiba1/Ebooks/bibles

```

== Verse References
In addition to the text, the New American Bible online 
provides comments as well as links / references for some verses.

== Maven build command with tag:
```
mvn -Dsia.bible.nab.metadata.folder=/media/kiet/toshiba1/Ebooks/bibles/metadata/nab -Dsia.bible.nab.text.folder=/media/kiet/toshiba1/Ebooks/bibles/nab -Dsia.bible.rsv.text.folder=/media/kiet/toshiba1/Ebooks/bibles/rsv -Dsia.bible.dr.text.folder=/media/kiet/toshiba1/Ebooks/bibles/dr -Dsia.bible.lv.text.folder=/media/kiet/toshiba1/Ebooks/bibles/lv -Dsonar.host.url=http://localhost:9000 -Dsonar.login=9f40da8a3d273cd1d47f0f038d054dba883c1c7b -Dsonar.login=admin -Dsonar.password=admin install test sonar:sonar
```





